"""empty message

Revision ID: 028f9f81f6ff
Revises: 789b2bf602d6
Create Date: 2020-02-14 13:41:20.472020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028f9f81f6ff'
down_revision = '789b2bf602d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_pitchedss_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'pitchedss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitchedss', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_pitchedss_fkey', 'comments', 'pitched', ['pitchedss'], ['id'])
    # ### end Alembic commands ###
