"""DED

Revision ID: 22be24581010
Revises: eb30c9baa341
Create Date: 2020-02-12 16:14:47.071435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22be24581010'
down_revision = 'eb30c9baa341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitched',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitches', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitch',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pitches', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pitch_pkey')
    )
    op.drop_table('pitched')
    # ### end Alembic commands ###
