"""SSSS

Revision ID: 2ba0a57f790e
Revises: 2ec10b2814da
Create Date: 2020-02-13 09:23:04.499272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba0a57f790e'
down_revision = '2ec10b2814da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.drop_constraint('person_pitches_id_fkey', 'person', type_='foreignkey')
    op.create_foreign_key(None, 'person', 'pitched', ['pitch_id'], ['id'])
    op.drop_column('person', 'pitches_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('pitches_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.create_foreign_key('person_pitches_id_fkey', 'person', 'pitched', ['pitches_id'], ['id'])
    op.drop_column('person', 'pitch_id')
    # ### end Alembic commands ###
