"""SSSS

Revision ID: 2ec10b2814da
Revises: 22be24581010
Create Date: 2020-02-13 08:45:07.393209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec10b2814da'
down_revision = '22be24581010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('pitches_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'person', 'pitched', ['pitches_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'pitches_id')
    # ### end Alembic commands ###
