"""SSSS

Revision ID: 33f8d2a8bdb3
Revises: 464dea422585
Create Date: 2020-02-13 14:01:29.226219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f8d2a8bdb3'
down_revision = '464dea422585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pitched_user_id_fkey', 'pitched', type_='foreignkey')
    op.drop_column('pitched', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitched', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitched_user_id_fkey', 'pitched', 'person', ['user_id'], ['id'])
    # ### end Alembic commands ###
