"""SSSS

Revision ID: 464dea422585
Revises: b974c0a078ad
Create Date: 2020-02-13 11:31:53.314152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464dea422585'
down_revision = 'b974c0a078ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pitched', 'person', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitched', type_='foreignkey')
    # ### end Alembic commands ###
