"""empty message

Revision ID: 789b2bf602d6
Revises: eab9c08d5bdd
Create Date: 2020-02-14 09:33:53.523103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789b2bf602d6'
down_revision = 'eab9c08d5bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitchedss', sa.Integer(), nullable=True))
    op.drop_constraint('comments_pitch_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'pitched', ['pitchedss'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_pitch_id_fkey', 'comments', 'pitched', ['pitch_id'], ['id'])
    op.drop_column('comments', 'pitchedss')
    # ### end Alembic commands ###
