"""create migration

Revision ID: 84922b57e363
Revises: c47c592022b0
Create Date: 2020-02-11 14:17:34.125091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84922b57e363'
down_revision = 'c47c592022b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.add_column('person', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_person_email'), 'person', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_email'), table_name='person')
    op.drop_column('person', 'email')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('secure_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
