"""add user

Revision ID: 861b7fd13535
Revises: 21f3b66235f3
Create Date: 2020-02-10 15:34:48.153807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861b7fd13535'
down_revision = '21f3b66235f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
