"""add user

Revision ID: c47c592022b0
Revises: b98fc19e1bcd
Create Date: 2020-02-10 15:52:58.293645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47c592022b0'
down_revision = 'b98fc19e1bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secure_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secure_password')
    # ### end Alembic commands ###
