"""SSSS

Revision ID: fbf5d31ee1d9
Revises: 33f8d2a8bdb3
Create Date: 2020-02-13 16:17:58.963909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf5d31ee1d9'
down_revision = '33f8d2a8bdb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitched', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitched', 'person', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitched', type_='foreignkey')
    op.drop_column('pitched', 'user_id')
    # ### end Alembic commands ###
